// src/screens/client/trainingStyles.js
import { StyleSheet } from 'react-native';

export const trainingStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F7FA' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  logo: { fontSize: 20, fontWeight: '700', color: '#1A1A1A' },
  headerIcons: { flexDirection: 'row' },
  iconButton: { marginLeft: 16 },
  dateNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    marginBottom: 8,
  },
  navArrow: { padding: 8 },
  dateText: { fontSize: 16, fontWeight: '500', color: '#1A1A1A' },
  content: { padding: 16, paddingBottom: 32 },
  exerciseCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  activeCard: {
    backgroundColor: '#F9FAFB',
    shadowOpacity: 0.1,
    elevation: 4,
  },
  exerciseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  dragHandle: { marginRight: 12 },
  exerciseName: { fontSize: 18, fontWeight: '600', color: '#1A1A1A', flex: 1 },
  addApproachButton: { padding: 4 },
  approachHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    marginBottom: 8,
  },
  headerNumber: { width: 30, fontWeight: '600', color: '#6B7280' },
  headerMetric: { flex: 1, fontWeight: '600', color: '#6B7280', textAlign: 'center' },
  headerDone: { width: 60, textAlign: 'center', fontWeight: '600', color: '#6B7280' },
  approachRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  approachNumber: { width: 30, fontWeight: '500', color: '#1A1A1A' },
  metricContainer: { flex: 1, alignItems: 'center' },
  metricLabel: { fontSize: 10, color: '#9CA3AF', marginBottom: 2 },
  metricValue: { fontSize: 14, fontWeight: '500', color: '#1F2937' },
  checkbox: { width: 60, alignItems: 'center' },
  emptyTrainingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  noTrainingText: { fontSize: 16, color: '#6B7280', marginBottom: 20 },
  startButton: {
    flexDirection: 'row',
    backgroundColor: '#4F46E5',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 30,
    alignItems: 'center',
  },
  startButtonText: { color: '#fff', fontSize: 16, fontWeight: '600', marginLeft: 8 },
  headerButtons: {
  flexDirection: 'row',
  alignItems: 'center',
  },
  addApproachButton: { padding: 4, marginRight: 8 },
  deleteButton: { padding: 4 },
});